# Generated by Django 5.0.1 on 2024-02-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=9)),
                ('comentario', models.TextField()),
                ('archive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.IntegerField()),
                ('img', models.CharField(max_length=255)),
                ('bedType', models.CharField(max_length=255)),
                ('facilities', models.JSONField()),
                ('rate', models.FloatField()),
                ('offerPrice', models.FloatField()),
                ('status', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nota', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.rooms')),
            ],
        ),
    ]
